services:
  proxy:
    build:
      context: ./proxy/
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        DOMAIN: ${DOMAIN}
    container_name: "proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./proxy/ssl/:/ssl/"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  front-end:
    container_name: front-end
    build:
      context: ./front-end
      target: development
    env_file:
      - ./front-end/.env
    environment:
      BACKEND_URL: http://back-end/api
    develop:
      watch:
        - action: sync
          path: ./front-end/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./front-end/package.json
    labels:
      traefik.http.routers.front-end.rule: Host(`${DOMAIN}`)
      traefik.http.routers.front-end.tls: true

  back-end:
    container_name: back-end
    build:
      context: ./back-end
      target: development
    entrypoint: >
      /bin/sh -c "
      php artisan migrate --force &&
      apache2-foreground"
    environment:
      DB_HOST: db
    env_file:
      - ./back-end/.env
    develop:
      watch:
        - action: sync
          path: ./back-end
          target: /var/www/html
        - action: rebuild
          path: ./back-end/composer.json
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - geoprofs_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}" ]
      interval: 1s
      timeout: 5s
      retries: 50

volumes:
  geoprofs_postgres_data: