services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end
    restart: unless-stopped
    volumes:
      - ./front-end:/app
    ports:
      - "80:3000"

  back-end:
    container_name: back-end
    build:
      context: ./back-end
    restart: unless-stopped
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
