services:
  proxy:
    build:
      context: ./proxy/
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        DOMAIN: ${DOMAIN}
    container_name: "proxy"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./proxy/ssl/:/ssl/"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  front-end:
    container_name: front-end
    build:
      context: ./front-end
    restart: unless-stopped
    volumes:
      - ./front-end:/app
    labels:
      traefik.enable: true
      traefik.http.routers.front-end.rule: Host(`${DOMAIN}`)
      traefik.http.routers.front-end.tls: true

  back-end:
    container_name: back-end
    build:
      context: ./back-end
    restart: unless-stopped
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/var/www/html
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.backend-end.rule: Host(`${DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.backend-end.tls: true

  db:
    container_name: db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
