apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoprofs-backend-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoprofs-backend-deployment
  template:
    metadata:
      labels:
        app: geoprofs-backend-deployment
    spec:
      initContainers:
        - name: geoprofs-migrate
          image: rutger505/geoprofs-backend:${TAG}
          command: [ "sh", "-c", "php artisan db:create && php artisan migrate" ]
          envFrom:
            - configMapRef:
                name: geoprofs-config
            - secretRef:
                name: geoprofs-secret
      containers:
        - name: geoprofs-backend
          image: rutger505/geoprofs-backend:${TAG}
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: geoprofs-config
            - secretRef:
                name: geoprofs-secret
