apiVersion: v1
kind: ConfigMap
metadata:
  name: geoprofs-config
  namespace: ${NAMESPACE}
data:
  APP_NAME: "geoprofs-back-end"
  APP_ENV: "local" #TODO set
  APP_DEBUG: "true" #TODO set
  APP_TIMEZONE: "UTC"
  APP_URL: "${BASE_URL}"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug" # TODO set
  L5_SWAGGER_USE_ABSOLUTE_PATH: "false" # TODO check if correctly interpreted
