apiVersion: v1
kind: ConfigMap
metadata:
  name: geoprofs-config
  namespace: ${NAMESPACE}
data:
  APP_NAME: "geoprofs-back-end"
  APP_ENV: "${LARAVEL_APP_ENV}"
  APP_DEBUG: "${LARAVEL_APP_DEBUG}"
  APP_TIMEZONE: "UTC"
  APP_URL: "${BASE_URL}"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "${LARAVEL_LOG_LEVEL}"
  L5_SWAGGER_USE_ABSOLUTE_PATH: "false" # TODO check if correctly interpreted
