apiVersion: v1
kind: ConfigMap
metadata:
  name: geoprofs-config
  namespace: ${NAMESPACE}
data:
  APP_NAME: "geoprofs-back-end"
  APP_ENV: "${LARAVEL_APP_ENV}"
  APP_DEBUG: "${LARAVEL_APP_DEBUG}"
  APP_TIMEZONE: "UTC"
  APP_URL: "${BASE_URL}"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "${LARAVEL_LOG_LEVEL}"
  L5_SWAGGER_USE_ABSOLUTE_PATH: "false" # TODO check if correctly interpreted
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "465"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_NAME: "Geoprofs verlofsysteem"
  NEXT_PUBLIC_BACKEND_URL: "https://${INGRESS_HOST}/api"
  BACKEND_URL: "http://geoprofs-backend-service.${NAMESPACE}.svc.cluster.local/api"
