apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoprofs-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoprofs-deployment
  template:
    metadata:
      labels:
        app: geoprofs-deployment
    spec:
      initContainers:
        - name: geoprofs-migrate
          image: rutger505/geoprofs-backend:${TAG}
          command: ["sh", "-c", "echo $(POSTGRES_URL) && php artisan migrate"]
          envFrom:
            - configMapRef:
                name: geoprofs-config
            - secretRef:
                name: geoprofs-secret

      containers:
        - name: geoprofs-frontend
          image: rutger505/geoprofs-frontend:${TAG}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: geoprofs-config
            - secretRef:
                name: geoprofs-secret
        - name: geoprofs-backend
          image: rutger505/geoprofs-backend:${TAG}
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: geoprofs-config
            - secretRef:
                name: geoprofs-secret
