apiVersion: v1
kind: Secret
metadata:
  name: geoprofs-secret
  namespace: ${NAMESPACE}
stringData:
  APP_KEY: "${LARAVEL_APP_KEY}"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-service.${POSTGRES_NAMESPACE}.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "geoprofs"
  DB_USERNAME: "${POSTGRES_USER}"
  DB_PASSWORD: "${POSTGRES_PASSWORD}"