name: Test and run SonarCloud Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-front-end:
    name: Test front-end
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies
        working-directory: ./front-end
        run: npm ci

      - name: Run tests with coverage
        working-directory: ./front-end
        run: npm run test:coverage

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: front-end/coverage

  sonar:
    needs: [test-front-end]
    if: always()
    name: SonarQube front-end
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: coverage
          path: front-end/coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
