name: Test Front End

on:
  pull_request:
    branches:
      - '*'


jobs:
  test:
    name: Test Front End
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./front-end

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
